### ISSUE TITLE
Not enough contrast in badge icon when all jobs are ok

### ISSUE THREAD

**Issue by timbeadle** [justlaputa/jenkins-monitor#25]
![screen shot 2016-12-07 at 16 35 05](https://cloud.githubusercontent.com/assets/752114/20976674/2579cc72-bc9b-11e6-8e2d-c4006f3d1179.png)

When no builds are failing, the white text on the bright green background colour does not provide enough contrast to easily read the number of jobs.

Need to make the green darker, or switch to a dark text colour.

**Comment by justlaputa** [comment]
Got it! I will work on it soon.

Thanks!

**Comment by timbeadle** [comment]
@justlaputa thank you!

**Comment by justlaputa** [comment]
fixed by c918503b
